version: '2.0'

services:
  myvue:
    image: nickbryant/vue:myVueSite-1.0.0
    container_name: myvue
    restart: always
    ports:
      - "8085:8085"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/nginx/conf.d/myvue.conf:/etc/nginx/conf.d/myvue.conf
      - /usr/local/project/myVue/dist/:/usr/share/nginx/html/
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-net

networks:
  app-net:
    external: true